package it.polimi.ingsw.Enums;

public enum ActionType {
    SETUP,
    ROUND_SETUP,
    DRAW_STUDENT,
    STUDENT_TO_BAG,
    ADD_STUDENT_ISLAND,
    REMOVE_STUDENT_ISLAND,
    ADD_STUDENT_DR,
    REMOVE_STUDENT_DR,
    ADD_STUDENT_ENTRANCE,
    REMOVE_STUDENT_ENTRANCE,
    MOVE_MN,
    EMPTY_CLOUD,
    MERGE_ISLANDS,
    CHOOSE_ASSISTANT_CARD,
    CHOSE_CHARACTER_CARD,
    PLACE_TOWER,
    REMOVE_TOWER,
    ASSIGN_PROFESSORS,
    CONQUER_ISLAND,
    PLACE_NE_TILE,
    REMOVE_NE_TILE,
    ASSIGN_COIN,
    PURCHASE_CARD;
}
